baseURL: "https://shenyiming.info/"
languageCode: "zh-cn"
title: "Yiming Shen"
theme: "hugo-profile"
publishDir: "docs"
outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"
    
Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
googleAnalytics: G-01JKXLCFQB

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blogs
      weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Yiming Shen"
  description: "CTFer, Web3 & Blockchain Security."
  # staticPath: "/shenyiming.info"  # The path to serve the static files from
  favicon: "/fav.png"
  assets:
    disableFingerprinting: true
  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    brandName: "Yiming's Academic Page" # Brand name for the brand | default is the title variable
    disableSearch: true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false
  # Hero
  hero:
    enable: true
    intro: "👋 Hi, there! I'm"
    title: "Yiming Shen"
    subtitle: "CTFer, Web3 & Blockchain Security"
    content: "Trying to unravel the mysteries of Web3 and uncover the hidden risks in blockchain to pave the way for a more secure digital landscape."
    image: /fav.png
    button:
      enable: true
      name: "Resume"
      url: "/cv/ShenYiming_20220925.pdf"
      download: false
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/shenyimings
        - icon: fab fa-instagram
          url: https://www.instagram.com/shenyimings/
        - icon: fab fa-zhihu
          url: https://www.zhihu.com/people/shen-yi-ming-91
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me3.png"
    content: |-
      I am a student of information security and cryptology, with a focus on web3 and blockchain security. My participation in web penetration and CTF events has sparked my interest in this field. I have dedicated myself to extensive research in uncovering the hidden risks and vulnerabilities in web3 security and blockchain security and hope to pave the way for a more secure digital landscape. With that aim, I am eager to further my education and gain practical experience in the area of cryptology and blockchain security.

      -
    skills:
      enable: true
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML CSS JavaScript"
        - "WeChat Miniprogram"
        - "Ethers.js & Hardhat"
        - "Solidity"
        - "Python"
        - "LaTex & Markdown"

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Penetration Test Engineer Intern"
        company: "SD Sanet"
        companyUrl: "https://t.wangan.com/c/c328277ce0e7e4abe"
        date: "Jun 2022 - Sep 2022"
        featuredLink:
          enable: true
          name: "View the proof"
          url: "image"
        content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

      - job: "Penetration Test Engineer Intern"
        company: "Yantai Public Security Bureau"
        companyUrl: "https://example.com"
        date: "Sep 2020 - Dec 2021"
        featuredLink:
          enable: true
          url: "https://example.com"
          name: "View the proof"
        info:
          enable: true
          content: I worked as a software developer for more than one year in Amazon.
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead backend developer for a product.
          - Created a frontend design for a product.

      - job: "Research: ML-based smart contract vuln analysis"
        company: "Science Research"
        companyUrl: "https://github.com/shenyimings/Intellicon"
        date: "Oct 2022 - Today"
        info:
          enable: true
        featuredLink:
          enable: true
          url: "https://example.com"
          name: "View the article"
        content: |
          I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

          - Lead backend developer for a product.
          - Created a frontend design for a product.


  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      # - title: "Master of Business Administration"
      #   school:
      #     name: "University of California, Berkeley"
      #     url: "https://example.org"
      #   date: "2013 - 2015"
      #   GPA: "3.8 out of 5.0"
      #   content: |-
      #     Extracurricular Activities
      #       - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      #       - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      - title: "Bachelor of Cyberspace Security"
        school:
          name: "School of Cyberspace Security, Hainan University"
          url: "https://www.hainanu.edu.cn/"
        date: "2020 - 2024"
        GPA: "3.6 out of 4.0"
        content: |-
          I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
          - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
          - Face mask detection using a single convolutional neural network.

          Extracurricular Activities
            - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
            - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
        # award and honor
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"
      # - title: "High School"
      #   school:
      #     name: "Thomas Jefferson High School for Science and Technology."
      #     url: "https://example.org"
      #   GPA: "4.2 out of 5.0"
      #   featuredLink:
      #     enable: true
      #     url: "https://example.com"

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: false
    # title: "Custom Name"
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        badges:
          - "Django"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    email: seuilping@outlook.com
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    # socialNetworks:
    #   github: https://github.com
    #   linkedin: https://linkedin.com
    #   twitter: https://twitter.com
    #   instagram: https://instagram.com
    #   facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false