[build]
publish = "public"
command = 'echo -e "\ngoogleAnalytics: $GOOGLE_ANALYTICS \ndisqusShortname: $DISQUS_SHORTNAME \n" >> config.yaml && hugo --gc --minify --themesDir theme/hugo-profile'

[context.production.environment]
HUGO_VERSION = "0.92.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
HUGO_THEME = "hugo-profile"

[context.split1]
command = "hugo --gc --minify --enableGitInfo --themesDir theme/hugo-profile"

[context.split1.environment]
HUGO_VERSION = "0.92.0"
HUGO_ENV = "production"
HUGO_THEME = "hugo-profile"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture --themesDir theme/hugo-profile -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.92.0"
HUGO_THEME = "repo"

[context.branch-deploy]
command = "hugo --gc --minify --themesDir theme/hugo-profile -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.92.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
